### ISSUE TITLE
Buffer overrun errors

### ISSUE THREAD

**Issue by XayOn** [ambrop72/aprinter#17]
I'm getting some buffer overrun errors. 
With the following procedure:
- Put Z axis as far away as it gets.
- Start printing
- Wait

It seems like octoprint keeps sending commands without waiting for the Z axis to go home (should be non-blocking).
Then, when the Z axis gets home, I get the buffer overrun error. 

No more info by the moment but can reproduce it anytime. Anyway It's not usual to have it waiting for like 10s (wich is what takes for my z axis to go full down from up top) so it's not a big deal

**Comment by ambrop72** [comment]
This must be an issue with the host software sending too many commands without waiting for ok, so closing.
