### ISSUE TITLE
Chaning bed probing parameters doesn't seem to have effect

### ISSUE THREAD

**Issue by edwinmat** [ambrop72/aprinter#20]
When I enable bed probing, changing (at least) the OffsetX and OffsetY parameters and the ProbePoints doesn't have any effect in the generated JSON (and probably code). Default probing points are (0,31), (0,155), (205,31) and (205,155), OffsetX is -18 and OffsetY is -31.

**Comment by ambrop72** [comment]
Huh, are you sure? Could it be you're changing them in the wrong Configuration, or looking at the wrong one in the JSON file? Or you're expecting these to have immediate effect upon flashing the firmware while the firmware is loading stored configuration on EEPROM?

**Comment by edwinmat** [comment]
No I was only talking about the generated JSON when I press the 'export data' button. I was not in the stage of flashing and storing something in the EEPROM yet. But I think I found my 'mistake' (or at least a workaround): you first need to press 'save data' before the data can be exported.

**Comment by ambrop72** [comment]
The "export" button should export whatever is currently in the editor, the "save data" only affects what is loaded when you reload the editor.

**Comment by edwinmat** [comment]
Ah I just found out that the export button exports all data (all examples, all boards). I was changing the RAMPS bed levelling parameters and by coincidence the first section I found in the JSON was the 4pi example with completely other probepoints. Sorry for the confusion.
